/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import eventsSidebar from "./docs/api/events/sidebar";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "html",
      value: "Getting Started", // The text to display
      className: "non-clickable-label", // Add a custom CSS class
    },
    {
      type: "autogenerated",
      dirName: "docs",
    },
  ],
  api: [
    {
      type: "doc",
      id: "api/overview",
    },
    {
      type: "category",
      label: "Events",
      items: [eventsSidebar],
    },
  ],
};

export default sidebars;
