name: CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      build_number:
        description: "Build Number"
        required: true
        default: "new"
      environment:
        description: "Environment variable for test"
        required: false
        default: "staging"
      grep_pattern:
        description: "Pattern for grep to filter tests"
        required: false
        default: "regression"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  cd:
    name: "cd"
    needs: [ci]
    permissions:
      id-token: write
      contents: read
      packages: read
    if: github.ref_name == 'main'
    uses: coinify-v2/reusable-workflows/.github/workflows/deploy-ecs.yml@main
    secrets: inherit
    with:
      cluster: coinify-sandbox
      service: docs
      container: docs
      repository: docs
      region: us-east-1
      workload_role: arn:aws:iam::474668381756:role/GithubDeploymentRole
      environment: sandbox
      docker_file: Dockerfile
      build_context: .
